[package]
name = "vhost_backend"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
libc = ">=0.2.39"

memory_model = { path = "../memory_model" }
vhost_gen = { path = "../vhost_gen" }
sys_util = { path = "../sys_util" }
